couchbaselabs/couchbase-rs

appveyor.yml
Add AppVeyor configuration for issue #16 - Config copied from https://github.com/starkat99/appveyor-rust/
Taken from the repo:
> The default template is sufficient for a basic Rust project that builds on both 32-bit and 64-bit windows targets for both MSVC and GNU toolchains across all three Rust channels (stable, beta, and nightly).
=> add appveyor configuration

.gitignore, couchbase/Cargo.toml, couchbase/examples/analytics_simple.rs, couchbase/examples/kv_basics.rs, couchbase/examples/kv_mutate.rs, couchbase/examples/kv_subdoc_lookup.rs, couchbase/examples/kv_subdoc_mutate.rs, couchbase/examples/query_decoding.rs, couchbase/examples/query_parameters.rs, couchbase/examples/query_simple.rs, couchbase/src/bucket.rs, couchbase/src/cluster.rs, couchbase/src/collection.rs, couchbase/src/error.rs, couchbase/src/instance/mod.rs, couchbase/src/instance/request.rs, couchbase/src/result.rs
This commit switches from futures 0.1 to the new async/await syntax. It
requires Rust 1.39+, currently in beta. Additionally, it switches from
`std::sync::Mutex` to the futures-safe Mutex from `futures-preview`.
This should solve deadlock problems when running on multi-threaded
futures executors, such as tokio.
All tests pass, and the rustdoc is updated.
=> feature: Convert to async/await

couchbase/src/api/search.rs, couchbase/src/api/search_indexes.rs, couchbase/src/io/lcb/callbacks.rs, couchbase/src/io/lcb/mod.rs
This PR solves to issues I faced during building and compiling `couchbase-rs` on macos M1 and rust 1.65.0:
- `__va_list_tag` not found in this scope
- `serde::Serialize` and `serde_derive::Serialize` naming conflict
When trying to build `couchbase-rs` on macbook m1 or arm64-based docker image. The build process errors with: 
```bash
error[E0412]: cannot find type `__va_list_tag` in this scope
--> couchbase/src/io/lcb/callbacks.rs:1035:31
|
1035 | pub(crate) type VaList = *mut __va_list_tag;
|                               ^^^^^^^^^^^^^ not found in this scope
```
Additionally, when trying to integrate `couchbase-rs` in a rust project, I get Serialize macro/struct name conflict errors.
1. **Guard `VaList` definition with extra `target_os` and `target_arch` conditions**
If `target_arch` is …
=> fix: `__va_list_tag` not found

couchbase-sys/build/main.rs
This PR solves an issue I faced while running the kv example under macOS M1 and rust 1.65.0:
I have the following installed:
- clang `v11.1.0`
- cmake `v3.24.3`
- pkg-config `v0.29.2`
- openssl `v3.0.7`
- libevent `2.1.12`
- libiconv `v2.35`
Running with default features:
```
error: linking with `cc` failed: exit status: 1 ... ld: library not found for -lcouchbase
```
Running with default features + libcouchbase-static:
```
error: could not find native static library `couchbase`, perhaps an -L flag is missing?
```
Let rustc know the location of libcouchbase library
```rust
println!(
"cargo:rustc-link-search=native={}",
build_dst.join("build/lib").display()
);
```
- Tried to run tests, however, `Success: 0, Failures: 26, Skipped:`. most errors `Cannot dispatch operation because no open …
=> fix: library not found

sdk/couchbase-core/src/cbconfig/mod.rs, sdk/couchbase-core/src/error.rs, sdk/couchbase-core/src/kvclient.rs, sdk/couchbase-core/src/memdx/auth_mechanism.rs, sdk/couchbase-core/src/memdx/client.rs, sdk/couchbase-core/src/memdx/codec.rs, sdk/couchbase-core/src/memdx/connection.rs, sdk/couchbase-core/src/memdx/dispatcher.rs, sdk/couchbase-core/src/memdx/error.rs, sdk/couchbase-core/src/memdx/magic.rs, sdk/couchbase-core/src/memdx/op_auth_saslauto.rs, sdk/couchbase-core/src/memdx/op_auth_saslbyname.rs, sdk/couchbase-core/src/memdx/op_auth_saslplain.rs, sdk/couchbase-core/src/memdx/op_auth_saslscram.rs, sdk/couchbase-core/src/memdx/op_bootstrap.rs, sdk/couchbase-core/src/memdx/opcode.rs, sdk/couchbase-core/src/memdx/ops_core.rs, sdk/couchbase-core/src/memdx/ops_crud.rs, sdk/couchbase-core/src/memdx/pendingop.rs, sdk/couchbase-core/src/memdx/response.rs, sdk/couchbase-core/src/memdx/sync_helpers.rs
Motivation
----------
The memdx error model does not currently satisfy what we need from it. We need to be able to attach cluster configs and error context to errors sometimes.
Changes
--------
Rework memdx error model to include more types of error and the top level error be a struct.
=> Rework memdx error model

.github/workflows/build.yml, rust-toolchain.toml, sdk/couchbase-core/src/kvclientmanager.rs, sdk/couchbase-core/src/lib.rs, sdk/couchbase-core/src/vbucketrouter.rs
Motivation
----------
A primary design pattern that we want to use is currently challenging due to asybc closures not being supported in stable rust. In order to make this pattern possible we should switch to nightly and enable the feature. async_closures should be moved to stable before we need to release the SDK.
Changes
--------
Specify the nightly toolchain.
Enable async_closures feature.
Use async closures.
=> Move to nightly rust to access async closures

sdk/couchbase-core/src/authenticator.rs, sdk/couchbase-core/src/configwatcher.rs, sdk/couchbase-core/src/crudcomponent.rs, sdk/couchbase-core/src/kvclient.rs, sdk/couchbase-core/src/kvclientpool.rs
Motivation
----------
Authenticator being a trait makes it more difficult to work with than if it was an enum. It is intended to be a public facing interface but with private-only implementations. As we know all of the implementations we can just use an enum.
Changes
--------
Change authenticator to be an enum.
=> Change authenticator to be an enum

sdk/couchbase-core/Cargo.toml, sdk/couchbase-core/src/configwatcher.rs, sdk/couchbase-core/src/crudcomponent.rs, sdk/couchbase-core/src/kvclient.rs, sdk/couchbase-core/src/kvclientmanager.rs, sdk/couchbase-core/src/kvclientpool.rs, sdk/couchbase-core/src/lib.rs, sdk/couchbase-core/src/memdx/client.rs, sdk/couchbase-core/src/memdx/dispatcher.rs
Motivation
-----------
Using channels for things like orphan handler requires us to spin up new tasks, the flow is also a bit easier to follow with callbacks.
Changes
-------
Update orphan handling and connection close handling to use callbacks. Rewrite kvclientpool to make this possible.
=> Update memdx channel usage to use callbacks where possible

sdk/couchbase-core/Cargo.toml, sdk/couchbase-core/src/httpx/base.rs, sdk/couchbase-core/src/httpx/client.rs, sdk/couchbase-core/src/httpx/error.rs, sdk/couchbase-core/src/httpx/json_block_read.rs, sdk/couchbase-core/src/httpx/json_row_parser.rs, sdk/couchbase-core/src/httpx/json_row_stream.rs, sdk/couchbase-core/src/httpx/mod.rs, sdk/couchbase-core/src/httpx/raw_json_row_streamer.rs, sdk/couchbase-core/src/lib.rs, sdk/couchbase-core/tests/common/test_config.rs, sdk/couchbase-core/tests/http.rs
Changes
---------
- Created HTTP Client, wrapping reqwest
- Created custom JSON Row parser + stream
=> RSCBC-1: Implement HTTP Crate

.gitignore, Cargo.toml, sdk/couchbase-core/Cargo.toml, sdk/couchbase-core/src/kvclientpool.rs, sdk/couchbase-core/src/memdx/ops_crud.rs, sdk/couchbase-core/src/retryfailfast.rs, sdk/couchbase-core/tests/agent_ops.rs
Motivation
----------
In order to optimize allocations we first need a way to track them. This change adds capabilities to do so, and adds a simple illustrative test which prints out allocations rather than enforcing how many can occurt before failing.
Changes
--------
Add a dependency on dhat.
Add a feature flag to enable it.
Add a simple test using dhat for heap profiling.
=> RSCBC-32: Add allocation counting test

.github/workflows/sort.yml, Cargo.toml, sdk/couchbase-connstr/Cargo.toml, sdk/couchbase-connstr/src/error.rs, sdk/couchbase-connstr/src/lib.rs, sdk/couchbase/Cargo.toml, sdk/couchbase/src/clients/cluster_client.rs, sdk/couchbase/src/error.rs, sdk/couchbase/src/lib.rs
Motivation
-----------
Moving the connstr module to its own crate will improve the reusability and allow us to easily use it in testing the core.
=> RSCBC-578: Move connstr to its own crate

sdk/couchbase-core/src/cbconfig/mod.rs, sdk/couchbase-core/src/configparser.rs
Motivation
----------
Hostname in the ext node configs is not always populated in a single node cluster.
=> RSCBC-61: Update ext node configs to have optional hostname

sdk/couchbase-core/src/httpx/raw_json_row_streamer.rs, sdk/couchbase-core/src/queryx/query_respreader.rs, sdk/couchbase-core/src/searchx/error.rs, sdk/couchbase-core/src/searchx/search.rs, sdk/couchbase-core/src/searchx/search_json.rs, sdk/couchbase-core/src/searchx/search_respreader.rs, sdk/couchbase-core/tests/http.rs
Motivation
----------
We currently implement stream so that it streams all of the rows and then returns None, a user must then cfall read_epilog to finish reading items off the stream - e.g. metadata. This is actually quite challenging to do as a consumer of the json stream, it'd be better if the epilog was parsed as a part of the stream.
=> Rework json stream implementation

sdk/couchbase-core/src/agent.rs, sdk/couchbase-core/src/memdx/op_bootstrap.rs, sdk/couchbase/Cargo.toml, sdk/couchbase/benches/collection_crud.rs, sdk/couchbase/benches/query.rs, sdk/couchbase/src/clients/agent_provider.rs, sdk/couchbase/src/clients/analytics_client.rs, sdk/couchbase/src/clients/bucket_client.rs, sdk/couchbase/src/clients/cluster_client.rs, sdk/couchbase/src/clients/collection_client.rs, sdk/couchbase/src/clients/couchbase_core_kv_client.rs, sdk/couchbase/src/clients/mod.rs, sdk/couchbase/src/clients/query_client.rs, sdk/couchbase/src/clients/scope_client.rs, sdk/couchbase/src/clients/search_client.rs, sdk/couchbase/src/cluster.rs, sdk/couchbase/tests/bucket.rs, sdk/couchbase/tests/collection_crud.rs, sdk/couchbase/tests/common/test_config.rs, sdk/couchbase/tests/query.rs, sdk/couchbase/tests/search.rs
Motivation
----------
The call to cluster.bucket is supposed to be synchronous and not return a result. At present it's async and has an unwrap in it.
Changes
-------
Add an agent provider which spawns a task to get an agent at the bucket level.
Obtain agents in clients via the provider.
=> RSCBC-64: Make opening a bucket a background task

sdk/couchbase-connstr/src/lib.rs, sdk/couchbase-core/src/agent.rs, sdk/couchbase-core/src/error.rs, sdk/couchbase-core/src/httpcomponent.rs, sdk/couchbase-core/src/lib.rs, sdk/couchbase-core/src/mgmtx/error.rs, sdk/couchbase-core/src/mgmtx/mgmt.rs, sdk/couchbase-core/src/mgmtx/mod.rs, sdk/couchbase-core/src/util.rs, sdk/couchbase/src/clients/cluster_client.rs, sdk/couchbase/tests/common/test_config.rs
Motivation
-----------
We currently cannot bootstrap a bucket agent against a non-kv node because select bucket fails. We need to add a http fallback to try fetch the config if all memd nodes fail.
=> RSCBC-65: Add http fallback for fetching first config

sdk/couchbase-core/Cargo.toml, sdk/couchbase-core/src/mgmtx/mgmt.rs
serde_urlencoded appears to be a bit out of maintainance and is not actually developed by the serde developers. We can perform url encoding with the url crate which we also already import.
=> RSCBC-10: Remove serde_urlencoded

sdk/couchbase-core/src/ondemand_agentmanager.rs, sdk/couchbase-core/tests/agent_manager.rs, sdk/couchbase/src/clients/cluster_client.rs, sdk/couchbase/src/cluster.rs
The closed check actually creates a race inside of get_bucket_agent. Agents need to gracefully handle having operations called on them once they've been closed anyway so the extra check just makes the signature of get_cluster_agent harder to work with.
=> Remove closed check for on demand agent manager

sdk/couchbase-core/src/searchx/query_options.rs, sdk/couchbase/src/search/vector.rs
Motivation
-----------
`k` has to be set in the search payload, and per RFC should default to 3
Changes
---------
Set num_candidates default to 3
=> RSCBC-134: VectorSearch num_candidates should set a default

sdk/couchbase-core/src/agent.rs, sdk/couchbase-core/src/configmanager.rs, sdk/couchbase-core/src/configwatcher.rs, sdk/couchbase-core/src/httpx/client.rs, sdk/couchbase-core/src/kvclient.rs, sdk/couchbase-core/src/kvclientmanager.rs, sdk/couchbase-core/src/kvclientpool.rs, sdk/couchbase-core/src/memdx/client.rs, sdk/couchbase-core/src/nmvbhandler.rs, sdk/couchbase-core/src/ondemand_agentmanager.rs, sdk/couchbase-core/tests/agent_manager.rs, sdk/couchbase-core/tests/agent_ops.rs, sdk/couchbase-core/tests/common/helpers.rs, sdk/couchbase-core/tests/common/test_agent.rs, sdk/couchbase-core/tests/mgmt.rs, sdk/couchbase/src/clients/agent_provider.rs, sdk/couchbase/src/clients/bucket_mgmt_client.rs, sdk/couchbase/src/clients/collections_mgmt_client.rs, sdk/couchbase/src/clients/couchbase_core_kv_client.rs, sdk/couchbase/src/clients/diagnostics_client.rs, sdk/couchbase/src/clients/query_client.rs, sdk/couchbase/src/clients/query_index_mgmt_client.rs, sdk/couchbase/src/clients/search_client.rs, sdk/couchbase/src/clients/search_index_mgmt_client.rs, sdk/couchbase/src/clients/user_mgmt_client.rs, sdk/couchbase/src/error.rs, sdk/couchbase/tests/connections.rs
Motivation
----------
When the top level resource, be it agent/agent manager/cluster, is dropped then all lower level resources such as connections should be dropped and tasks aborted.
Changes
-------
=> RSCBC-143: Updates to ensure dropping cluster/agent closes resources

sdk/couchbase-core/src/queryx/query_respreader.rs, sdk/couchbase-core/src/queryx/query_result.rs, sdk/couchbase-core/tests/query.rs, sdk/couchbase/src/options/query_options.rs, sdk/couchbase/src/results/query_results.rs, sdk/couchbase/tests/query.rs
Changes
---------
- Made QueryMetrics optional
- Default set `metrics` to false in the public API
=> RSCBC-168: Query result metrics is also present even when metrics are not requested
